### PR TITLE
OOB split + OOB fixes

### PR DESCRIPTION
**Pull request by himselfv**
1. Better plaintext generation for media messages on purple-backend.
2. Added an option 'oob_split' to split messages containing multiple media into several text-only/media-only messages, as certain XMPP clients [don't treat mixed types nicely](https://github.com/siacs/Conversations/issues/3419).
3. If 'oob_split' is disabled, Spectrum now processes all media in a message and OOB-wraps each. But until now it had this compatibility hack where it puts bare URI of the media in the plaintext. This is strictly speaking not proper by the standards (plaintext should match XHTML, and not be "URI only") and obviously doesn't scale to >1 media so I've added 'oob_replace_body' setting which if disabled disables it.

### CODE REVIEW

**Comment by vitalyster** [comment]
Some tests for new features?

**Comment by himselfv** [comment]
Something like this?

By the way. Is the code supposed to be C++98 compatible? It had been as far as I can tell, but [recent commits](https://github.com/SpectrumIM/spectrum2/commit/9aaff29c0e9c9ebecc9f71d14a6f8067b2257501#diff-3e491f314c46ac453349464f52828009) introduced `unique_ptr` and `nullptr`.

**Comment by vitalyster** [comment]
I think its better to use `boost::unique_ptr`

**Comment by himselfv** [comment]
That's also unavailable on boost < 1.58 or so. Maybe use `shared_ptr` in those two places?

**Comment by vitalyster** [comment]
Sure, shared_ptr (with swiften compat macro) used all over the code, but if unique_ptr is really needed we can copy boost implementation into source tree (there are already some boost headers)

**Comment by himselfv** [comment]
Done

**Pull request merged**
