### PR TITLE
Improved own message loopback tracking

### PR DESCRIPTION
**Pull request by himselfv**
Some protocols (purple-telegram) ignore outgoing message flags so the trick with PURPLE_MESSAGE_SPECTRUM2_ORIGINATED doesn't work.

This version stores outgoing messages for a few seconds and if in that time identical message "from us" is delivered it is ignored.

### CODE REVIEW

**Comment by vitalyster** [comment]
Can you try to add some test cases especially for "tricks" to be sure nothing broken now and in future?

**Comment by himselfv** [comment]
Something like this?

1. Added some binary tests for the outgoing message cache.

2. Added a few python tests for JabberServerModeConf configuration (carbon.py).

In the process:

3. Refactored python testing for more flexibility.

4. Reenabled the JabberServerModeConfg which had been disabled. Fixed some tests in that set.

5. Added special case handling to backend-libpurple: newly created XMPP MUC rooms have to be ``configure``d before they can be used. (Some tests have been broken because of this)

6. Please add ``python-dateutil`` to travic-cl's packages. It should've been a dependency of ``python-sleekxmpp``; without it some sleekxmpp plugins (xep_0054, xep_0203) silently fail to load and lead to weirdest errors.

Tests from #2 only cover carbons partially, but to test them better I'd need a libpurple backend which:

1. Delivers carbons to spectrum (prpl-jabber doesn't!)

2. Can be used in automated testing (purple-telegram does deliver carbons but the network can't be run locally)

**Comment by vitalyster** [comment]
https://github.com/SpectrumIM/spectrum2/blob/master/.travis.yml#L25 - python-dateutil can be added there

**Comment by vitalyster** [comment]
> Delivers carbons to spectrum (prpl-jabber doesn't!)

We can try to include 3rd party plugin for that - https://github.com/gkdr/carbons

**Comment by vitalyster** [comment]
Is it ready to merge?

**Comment by vitalyster** [comment]
Also - is that loopback tracker only needed for buggy prpl-telegram? Can you make it optional, non-default and enabled explicitly only if protocol = 'prpl-telegram'?

**Comment by vitalyster** [comment]
Also should we remove it when prpl-telegram will be fixed? :)

**Comment by himselfv** [comment]
Not ready, still going to try this:
> We can try to include 3rd party plugin for that - https://github.com/gkdr/carbons

Loopback tracker is needed for a different purpose:
```
User -> XMPP -> Spectrum: "Message A"

Spectrum -> libpurple: "Outgoing: User: Message A"

libpurple -> Spectrum: "Incoming: User: Message A"
//A copy of what we've just sent; ignore

libpurple -> Spectrum: "Incoming: User: Message B"
//A carbon of our text on the legacy network: forward to the user
```

We've no way of telling which message is a copy and which is new.

Previously I used a hack with a flag:
{code}
Spectrum -> libpurple: "Outgoing: User: Message A;  FLAG_SPECTRUM2_ORIGINATED"

libpurple -> Spectrum: "Incoming: User: Message A;  FLAG_SPECTRUM2_ORIGINATED"
//Have a flag; ignore the message

libpurple -> Spectrum: "Incoming: User: Message B"
//No flag; pass the message as XMPP carbon
{code}

But some protocols do not pass the same flags back. This is not a bug, they are not required to. For instance purple-telegram doesn't.

So loopback tracker now stores all outgoing messages for a few seconds and if we receive the same message, it's ignored. Otherwise it's a new message and it's forwarded as a carbon.

**Comment by vitalyster** [comment]
> https://github.com/gkdr/carbons

I think we need to package this plugin into spectrum repo, I will try to do it.

> some protocols

I think we need to report bugs to these protocols.

**Comment by himselfv** [comment]
They really don't have to. This is a non-standard flag. Even if it was a standard flag, there's no telling how the underlying network works: it might itself have no way to match "incoming" to "outgoing".

**Comment by himselfv** [comment]
> I think we need to package this plugin into spectrum repo

Maybe just clone & make & make install it from the .travis-ci?

**Comment by vitalyster** [comment]
`libpurple-xmpp-carbons1` is in xenial spectrum repo

**Comment by himselfv** [comment]
"carbons.so is not loadable: ABI version mismatch 2.12.x (need 2.10.x)" -- libpurple is 1:2.10 in xenial

By the way, what's the proper way to enable it? It loads when I make it locally but libpurple doesn't use it.

**Comment by vitalyster** [comment]
You need to put it to prefs.xml - https://github.com/SpectrumIM/spectrum2/commit/6df9b4bb7c81423285308224a17c364d57ba14e4

**Comment by himselfv** [comment]
Ohhh, it's /spectrum/plugins/loaded, thanks!

**Comment by vitalyster** [comment]
> carbons.so is not loadable

should be fixed now

**Comment by himselfv** [comment]
Yep, thanks! Still working on something. (Properly declaring carbon support by Spectrum + not wrapping carbons in ``<impersonate>`` in server mode)

**Comment by vitalyster** [comment]
I'm not sure we need server mode - it was added for tests before extended tests with prosody and never have good xmpp support

**Comment by vitalyster** [comment]
> it might itself have no way to match "incoming" to "outgoing"

But is there examples of such protocol plugins not counting prpl-telegram? It's known to be bad quality plugin

**Comment by himselfv** [comment]
> I'm not sure we need server mode - it was added for tests before extended tests with prosody

It's needed -- all tests currently use it:
```
Test client -> Spectrum (server-mode) -> libpurple (prpl-jabber) -> Prosody
```
But it's fine, I've added server-mode wrapping.

> is there an example of such protocol plugin not counting prpl-telegram?

From the standard ones, I think ICQ.

If I'm reading it right, the message is posted back automatically, preserving the flags, by libpurple if PurpleProtocolChatIface::send() implementation returns a value > 0.

This is [not documented](https://bitbucket.org/pidgin/main/src/026ac0b3708f22468c0bcbf282aa2055ff7c6d9e/libpurple/protocol.h?at=default&fileviewer=file-view-default#protocol.h-464), but if it returns 0 [the message is not posted](https://bitbucket.org/pidgin/main/src/026ac0b3708f22468c0bcbf282aa2055ff7c6d9e/libpurple/conversation.c?fileviewer=file-view-default#conversation.c-133).

Skypeweb and [jabber](https://bitbucket.org/pidgin/main/src/026ac0b3708f22468c0bcbf282aa2055ff7c6d9e/libpurple/protocols/jabber/message.c?at=default&fileviewer=file-view-default#message.c-1211) return 1 which is why the flag trick works.

[Facebook](https://bitbucket.org/pidgin/main/src/026ac0b3708f22468c0bcbf282aa2055ff7c6d9e/libpurple/protocols/facebook/facebook.c?at=default&fileviewer=file-view-default#facebook.c-1358), [IRC](https://bitbucket.org/pidgin/main/src/026ac0b3708f22468c0bcbf282aa2055ff7c6d9e/libpurple/protocols/irc/irc.c?at=default&fileviewer=file-view-default#irc.c-831) and [GGP](https://bitbucket.org/pidgin/main/src/026ac0b3708f22468c0bcbf282aa2055ff7c6d9e/libpurple/protocols/gg/chat.c?at=default&fileviewer=file-view-default#chat.c-471) all return 0 but repost the message manually, preserving flags.

Telegram [deliberately returns 0](https://github.com/majn/telegram-purple/blob/f38ea48ff088bd8d329a54d51f9fd1dd99f72a50/tgp-msg.c#L374). ICQ [returns 0](https://bitbucket.org/pidgin/main/src/026ac0b3708f22468c0bcbf282aa2055ff7c6d9e/libpurple/protocols/oscar/oscar.c?at=default&fileviewer=file-view-default#oscar.c-4349) too.

**Comment by himselfv** [comment]
Hope I got everything right :)

**Comment by vitalyster** [comment]
So it's ready to merge? Can you squash "should be" commits into logical one? :) It will be easy to find important changes later

**Comment by himselfv** [comment]
Sure, like this? Yep, should be ready to merge.

**Pull request merged**
