### PR TITLE
A bunch of packaging fixes

### LINKED ISSUE #270: Packages are built in debug mode, with optimisations disabled
Both the Debian and RPM packages are configured with `-DCMAKE_BUILD_TYPE=Debug`, causing compiler optimisations to be disabled completely (`-O0`). Is this intentional? I would assume that packages should normally be built with `-DCMAKE_BUILD_TYPE=Release`.

### PR DESCRIPTION
**Pull request by sicherha**
This pull request contains the following changes:
* Build Debian and RPM packages with optimisations enabled (fixes #270)
* Add missing build dependencies to the RPM .spec file
* Base the Docker image on the latest stable Fedora release instead of Fedora 23, which has been unsupported for over a year

### CODE REVIEW

**Comment by vitalyster** [comment]
are you sure latest fedora have libcommuni and libswiften?

**Comment by sicherha** [comment]
1. Both packages do exist on Fedora 27 - see https://apps.fedoraproject.org/packages/libcommuni and https://apps.fedoraproject.org/packages/swiften.
2. As far as I can see, the Copr repository seems to be largely abandoned. The last visible activity for the `spectrum2` package was back in May 2016 for Fedora 24.

I'm not sure what to make of the errors thrown by Travis - they seem to be unrelated to my commits. Looks more like an infrastructure problem to me:
`E: Failed to fetch https://packages.spectrum.im/spectrum2/dists/trusty/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed`

**Comment by vitalyster** [comment]
yes, trying to fix infrastructure there - https://github.com/SpectrumIM/spectrum2/tree/dockerfile.debian

**Comment by vitalyster** [comment]
> https://apps.fedoraproject.org/packages/swiften.
That is the old package from spectrum author made in 2016

**Comment by sicherha** [comment]
Done.

I wonder if it's a good idea to make the Docker image based on Debian? That would make it possible to use the pre-built Debian packages; only the libpurple backends would still have to be compiled from source.

**Comment by vitalyster** [comment]
Thanks, merged

**Comment by vitalyster** [comment]
@mcepl - can you please update your spectrum copr repository to recent package versions? :)

**Comment by mcepl** [comment]
https://copr.fedorainfracloud.org/coprs/build/714145/

**Comment by mcepl** [comment]
Err, I don't use ``*.spec`` file inside of the tarball (let's not go into flamewar about upstream maintained SPEC files), so I have missed you changed it. 

https://copr.fedorainfracloud.org/coprs/mcepl/spectrum2/build/714145/

**Comment by vitalyster** [comment]
Yes, I known your spec is different, how can I help to fix build on rawhide? Is it possible to add swiften4.0rc5?

**Comment by vitalyster** [comment]
@mcepl spectrum itself supports any recent boost version, but boost is also a dependency of libswiften which is outdated

**Comment by vitalyster** [comment]
So, please share swift packaging files too and I will try to update it

**Comment by mcepl** [comment]
> So, please share swift packaging files too and I will try to update it

These are just Fedora src.rpms from https://koji.fedoraproject.org/koji/packageinfo?packageID=10782 (actually I used https://kojipkgs.fedoraproject.org//packages/swift/3.0/0.6.rc2.fc24/src/swift-3.0-0.6.rc2.fc24.src.rpm ).

**Pull request closed without merging**
