### PR TITLE
Added multilevel support in roomlist

### LINKED ISSUE #201: Support multilevel in discovery
e.g. the discord libpurple implementation use multi level for server and channel:
(Image from the discord plugin added in pidgin)
image

But if i use the service discovery from xmpp it will only show the server and channel, but the channels do not have any attributes. So they cant be joined.
image

### PR DESCRIPTION
**Pull request by Fank**
Relates #201 

Example discord:

Before:
image

After:
image

### CODE REVIEW

**Comment by Fank** [comment]
Joining in discord current do not work, but that's an other issue i'm working on.

**Comment by Fank** [comment]
@vitalyster this is also ready to merge

**Comment by Fank** [comment]
rebased and green

**Comment by vitalyster** [comment]
This patch also contains "clean up" fixes and it makes me hard to understand it

**Comment by Fank** [comment]
also split?

**Comment by vitalyster** [comment]
if these fixes still not in clean up patch - please add it into that one

**Comment by Fank** [comment]
@vitalyster i cant, because my editor will clean open files, and can't do that for the whole project.
But you can use the whitespace hide functionality https://github.com/blog/967-github-secrets 

Add ?w=1 to the URL to see the diff with whitespace ignored.

**Comment by Fank** [comment]
i validated the cleanup changes is in #216

**Comment by Fank** [comment]
@vitalyster branch is now clean

**Comment by vitalyster** [comment]
Can you join these rooms now?

**Comment by Fank** [comment]
I havn't continued on the discord part jet, still not working.

**Comment by vitalyster** [comment]
So nothing to merge yet :)

**Comment by Fank** [comment]
i <3 automated scripts, entered wrong repo ... this should not be closed.

**Comment by vitalyster** [comment]
again???

**Comment by Fank** [comment]
Na i rechecked my PR's and noticed this is still open, but i ended all my xmpp related projects some month ago. so ill not continue this anymore.

**Comment by thundergreen** [comment]
@Fank NO GOOD NEWS!

**Comment by Fank** [comment]
Yea i know, but i'm still into developing stuff for discord so if someone would like to pick it up, than i could help. But i won't focus that.

**Comment by thundergreen** [comment]
@Fank did u ever hear about issue where either discord or spectrum send messages to muc when member leaves the channel? We tried to find the source of this message but could't find it. This makes channel use in xmpp impossible as muc will be flooded with leave messages

**Comment by vitalyster** [comment]
I hope references are stored in main repository, I will restore as new PRs for someone who will want to continue

**Pull request closed without merging**
